# Generated by Django 4.2.7 on 2025-07-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='id',
            new_name='loan_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='loan',
            new_name='loan_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='payment_id',
        ),
    ]
