# Generated by Django 4.2.7 on 2025-07-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_id_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
